[advisories]
version = 2

db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

yanked = "deny"

ignore = []

[licenses]
version = 2

allow = [
  # Effective public domain
  "Unlicense",

  # Attribution required
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Unicode-3.0",

  # Non-invasive copyleft
  "Apache-2.0",
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
deny = [
  { name = "serde_derive", version = ">=1.0.172, <1.0.185" },
  { name = "hashbrown", version = "=0.15.0" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  "https://github.com/kayabaNerve/crypto-bigint",
  "https://github.com/kayabaNerve/pasta_curves",
  "https://github.com/monero-oxide/monero-oxide",
]
