name: monero-regtest
description: Spawns a regtest Monero daemon

inputs:
  version:
    description: "Version to download and run"
    required: false
    default: v0.18.4.4

runs:
  using: "composite"
  steps:
    - name: Monero Daemon Cache
      id: cache-monerod
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # 4.2.4
      with:
        path: monerod*
        key: monerod-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Download the Monero Daemon
      if: steps.cache-monerod.outputs.cache-hit != 'true'
      shell: bash
      run: |
        OS=${{ runner.os }}
        ARCH=${{ runner.arch }}

        OS=$(echo "$OS" | tr "[:upper:]" "[:lower:]")
        ARCH=$(echo "$ARCH" | tr "[:upper:]" "[:lower:]")
        EXT="tar.bz2"

        if [ "$OS" = "windows" ]; then
          OS="win"
          EXT="zip"
        fi
        if [ "$ARCH" = "arm64" ]; then
          ARCH="armv8"
        fi
        if [ "$OS" = "macos" ]; then
          OS="mac"
          # If this is an ARM macOS downloading a historic version, download x64 to run via Rosetta
          if [ $(echo "${{ inputs.version }}" | cut -d'.' -f2) -lt 18 ]; then
            ARCH="x64"
          fi
        fi

        FILE=monero-$OS-$ARCH-${{ inputs.version }}.$EXT
        mkdir monero-tmp
        cd monero-tmp
        curl -L https://downloads.getmonero.org/cli/$FILE -o $FILE
        if [ "$EXT" = "tar.bz2" ]; then
          tar -xf $FILE
        fi
        if [ "$EXT" = "zip" ]; then
          unzip $FILE
        fi
        cd ..

        mv $(find . -type f -name "monerod*") .
        rm -rf monero-tmp

    - name: Monero Regtest Daemon
      shell: bash
      run: |
        COMMAND="./monerod --non-interactive --regtest --offline --fixed-difficulty=1
          --rpc-bind-port=18081 --rpc-login=monero:oxide"

        if [ "${{ runner.os }}" = "Windows" ]; then
          $COMMAND --install-service
          $COMMAND --start-service
        else
          $COMMAND --detach
        fi
