name: monero-regtest
description: Spawns a regtest Monero daemon

inputs:
  version:
    description: "Version to download and run"
    required: false
    default: v0.18.4.4

runs:
  using: "composite"
  steps:
    - name: Monero Daemon Cache
      id: cache-monerod
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # 4.2.4
      with:
        path: /usr/bin/monerod
        key: monerod-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Download the Monero Daemon
      if: steps.cache-monerod.outputs.cache-hit != 'true'
      shell: bash
      run: |
        OS=${{ runner.os }}
        ARCH=${{ runner.arch }}

        OS=$(echo "$OS" | tr "[:upper:]" "[:lower:]")
        ARCH=$(echo "$ARCH" | tr "[:upper:]" "[:lower:]")

        if [ "$OS" = "windows" ]; then
          OS=win
          echo "Windows is unsupported at this time"
          exit 1
        fi
        if [ "$OS" = "macos" ]; then
          OS=mac
        fi
        if [ "$ARCH" = "arm64" ]; then
          ARCH=armv8
        fi

        FILE=monero-$OS-$ARCH-${{ inputs.version }}.tar.bz2
        wget https://downloads.getmonero.org/cli/$FILE
        tar -xvf $FILE
        rm $FILE

        sudo mv $(find . -name monerod) /usr/bin/monerod
        sudo chmod 777 /usr/bin/monerod
        sudo chmod +x /usr/bin/monerod

    - name: Monero Regtest Daemon
      shell: bash
      run: |
        PATH=$PATH:/usr/bin monerod --non-interactive --regtest --offline --fixed-difficulty=1 \
          --no-zmq --rpc-bind-ip=0.0.0.0 --rpc-bind-port=18081 --confirm-external-bind \
          --rpc-access-control-origins "*" --disable-rpc-ban \
          --rpc-login=monero:oxide --log-level 2 \
          --detach
