name: monero-wallet-rpc
description: Spawns a Monero Wallet-RPC

inputs:
  version:
    description: "Version to download and run"
    required: false
    default: v0.18.4.4

runs:
  using: "composite"
  steps:
    - name: Monero Wallet RPC Cache
      id: cache-monero-wallet-rpc
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # 4.2.4
      with:
        path: monero-wallet-rpc
        key: monero-wallet-rpc-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Download the Monero Wallet RPC
      if: steps.cache-monero-wallet-rpc.outputs.cache-hit != 'true'
      # Calculates OS/ARCH to demonstrate it, yet then locks to linux-x64 due
      # to the contained folder not following the same naming scheme and
      # requiring further expansion not worth doing right now
      shell: bash
      run: |
        OS=${{ runner.os }}
        ARCH=${{ runner.arch }}

        OS=$(echo "$OS" | tr "[:upper:]" "[:lower:]")
        ARCH=$(echo "$ARCH" | tr "[:upper:]" "[:lower:]")

        if [ "$OS" = "windows" ]; then
          OS=win
          echo "Windows is unsupported at this time"
          exit 1
        fi
        if [ "$OS" = "macos" ]; then
          OS=mac
        fi
        if [ "$ARCH" = "arm64" ]; then
          ARCH=armv8
        fi

        FILE=monero-$RUNNER_OS-$RUNNER_ARCH-${{ inputs.version }}.tar.bz2
        wget https://downloads.getmonero.org/cli/$FILE
        tar -xvf $FILE

        mv monero-x86_64-linux-gnu-${{ inputs.version }}/monero-wallet-rpc monero-wallet-rpc

    - name: Monero Wallet RPC
      shell: bash
      run: |
        ./monero-wallet-rpc --allow-mismatched-daemon-version \
          --daemon-address 0.0.0.0:18081 --daemon-login monero:oxide \
          --disable-rpc-login --rpc-bind-port 18082 \
          --wallet-dir ./ \
          --detach
