name: no-std build

on:
  push:
    branches:
      - develop
    paths:
      - "crypto/**"
      - "networks/**"
      - "tests/no-std/**"

  pull_request:
    paths:
      - "crypto/**"
      - "networks/**"
      - "tests/no-std/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Install RISC-V Toolchain
        run: sudo apt update && sudo apt install -y gcc-riscv64-unknown-elf gcc-multilib && rustup +1.80 target add riscv32imac-unknown-none-elf

      - name: Verify no-std builds
        run: cd tests/no-std && CFLAGS=-I/usr/include cargo +1.80 build --target riscv32imac-unknown-none-elf
