name: Daily Deny Check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  verify-chain:
    name: Run monero-oxide-verify-chain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Build Dependencies
        uses: ./.github/actions/build-dependencies

      - name: Run monero-oxide-verify-chain
        run: |
          BLOCKS_ON_CHAIN=3500000

          PER_DAY=$(( $BLOCKS_ON_CHAIN / 28 ))
          DAY_OF_MONTH=$(( $(date +%d) - 1))
          START=$(( PER_DAY * DAY_OF_MONTH ))
          END=$(( $START + PER_DAY ))
          
          cargo run -p monero-oxide-verify-chain --release -- $START $END
