name: Monero Tests

on:
  push:
    branches:
      - main
    paths:
      - "monero-oxide/**"

  pull_request:
    paths:
      - "monero-oxide/**"

  workflow_dispatch:

jobs:
  # Only run these once since they will be consistent regardless of any node
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies

      - name: Run Unit Tests Without Features
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-io --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-generators --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-primitives --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-mlsag --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-clsag --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-borromean --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-bulletproofs --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-rpc --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-simple-request-rpc --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-address --lib
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet --lib

      - name: Run Unit Tests With Features
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-io --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-generators --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-primitives --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-mlsag --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-clsag --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-borromean --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-bulletproofs --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-rpc --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-simple-request-rpc --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-address --lib --all-features
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet --lib --all-features

      # Doesn't run unit tests with features as the tests workflow will

  integration-tests:
    runs-on: ubuntu-latest
    # Test against all supported protocol versions
    strategy:
      matrix:
        version: [v0.17.3.2, v0.18.3.4]

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          monero-version: ${{ matrix.version }}

      - name: Run Integration Tests Without Features
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-simple-request-rpc --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet --test '*'

      - name: Run Integration Tests
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --all-features --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-simple-request-rpc --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet --all-features --test '*'
